FORMAT: 1A
HOST: http://sitev4.iotsdk.com/v2

# Gizwits Site API v2

# Group API for passowrd protect question

## Question [/question]

### Get All Questions [GET]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

+ Response 200 (application/json)

    + Body
    
        {
          "questions": [{
            "id": 1,
            "content": "What's your name?"
          },{
            "id": 2,
            "content": "Where are you from?"
          }]
        }

## Answer [/answer]

### Register and Set Answer [POST]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

    + Body

        {
          "username": "15813269587",
          "password": "123456",
          "question_id": 1,
          "answer": "bob"
        }

+ Response 200 (application/json)


## Reset Password by Question [/reset_pwd]

### Reset Password by Question [POST]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

    + Body

        {
          "username": "15813269587",
          "question_id": 1,
          "answer": "bob"
          "new_pwd": "123456"
        }

+ Response 200 (application/json)
