FORMAT: 1A
HOST: http://sitev4.iotsdk.com/v2

# Gizwits Site API v2

# Group API for passowrd protect question

## Answer [/answer]

### Register and Set Answer [POST]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

    + Body

        {
          "username": "15813269587",
          "password": "123456",
          "question_id": 1,
          "answer": "bob"
        }

+ Response 200 (application/json)


## Answer [/answer/verify]

### Verify Answer [POST]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

    + Body

        {
          "username": "15813269587",
          "question_id": 1,
          "answer": "bob"
        }

+ Response 200 (application/json)

    + Body
    
        {
          "code": "abc"
        }

## Reset Password by Code [/reset_pwd]

### Reset Password by Code [POST]

+ Request (application/json)

    + Header

        Authorization: Basic a2VsbHk=

    + Body

        {
          "username": "15813269587",
          "new_pwd": "123456",
          "code": "abc"
        }

+ Response 200 (application/json)
